<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Highcharts Example</title>

		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript">
		$(function () {
            $('#power').highcharts({
                chart: {
                    type: 'line'
                },
                plotOptions: {
                    series: {
                        enableMouseTracking: false,
                        lineWidth: 1,
                        marker: {
                            enabled: false
                        }
                    }
                },
                title: {
                    text: 'Daily energy usage',
                    x: -20 //center
                },
                subtitle: {
                    text: 'pG stats',
                    x: -20
                },
                xAxis: {
                    categories: ['0','1','2','3','23'],
                    tickInterval: 12,
                    labels: {
                        enabled: true
                    }
                },
                yAxis: {
                    title: {
                        text: 'Energy (Watt)'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth: 0
                },
                series: [{
                    name: 'Power Usage',
                    data: [<?php echo $this->powerUsage; ?>]
                }, {
                    name: 'Power Return',
                    data: [<?php echo $this->powerReturn; ?>]
                }]
            });
        });

        $(function () {
            $('#daily_power').highcharts({
                chart: {
                    type: 'column'
                },
                plotOptions: {
                    column: {
                        stacking: 'normal',
                        dataLabels: {
                            enabled: false,
                            color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                            style: {
                                textShadow: '0 0 2px black, 0 0 2px black'
                            }
                        }
                    },
                    series: {
                        pointPadding: 0.1,
                        groupPadding: 0,
                        borderWidth: 0, 
                        shadow: false
                    },
                },
                title: {
                    text: 'Daily energy usage',
                    x: -20 //center
                },
                subtitle: {
                    text: 'last 30 days',
                    x: -20
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '11px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    title: {
                        text: 'Energy (KWh)'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth: 0
                },
                series: [{
                    name: 'Power Usage Total',
                    data: [<?php echo $this->powerUsageTotal; ?>],
                    color: '#FF0000'
                }, {
                    name: 'Power Return Total',
                    data: [<?php echo $this->powerReturnTotal; ?>],
                    color: 'green'
                }]
            });
        });

        $(function () {
            $('#daily_gas').highcharts({
                chart: {
                    type: 'column'
                },
                plotOptions: {
                    column: {
                        stacking: 'normal',
                        dataLabels: {
                            enabled: false,
                            color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                            style: {
                                textShadow: '0 0 2px black, 0 0 2px black'
                            }
                        }
                    }
                },
                title: {
                    text: 'Daily gas usage',
                    x: -20 //center
                },
                subtitle: {
                    text: 'last 30 days',
                    x: -20
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '11px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    title: {
                        text: 'Gas (m3)'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth: 0
                },
                series: [{
                    name: 'Gas Usage Total',
                    data: [<?php echo $this->gasTotal; ?>]
                }]
            });
        });
		</script>
</head>
<body>
    <script src="/module_energy/highchart401/js/highcharts.js"></script>
    <script src="/module_energy/highchart401/js/modules/exporting.js"></script>

    <div id="power" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <div id="daily_power" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <div id="daily_gas" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

</body>
</html>
