<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="/module_energy/highchart401/js/highcharts.js"></script>
<script src="/module_energy/highchart401/js/themes/dark-unica.js"></script>
<script type="text/javascript">
<!-- Generic Highcharts Config -->
$(function() {
    Highcharts.setOptions({
        exporting: {
            enabled: false
        },
        credits: {
            enabled: false
        }
    });
});

$(function () {
    $('#power').highcharts({
        chart: {
            type: 'line'
        },
        plotOptions: {
            series: {
                enableMouseTracking: false,
                lineWidth: 1,
                marker: {
                    enabled: false
                }
            }
        },
        title: {
            text: 'Daily energy usage'
        },
        subtitle: {
            text: 'pG stats'
        },
        xAxis: {
            categories: ['0','1','2','3','23'],
            tickInterval: 12,
            labels: {
                enabled: true
            }
        },
        yAxis: {
            title: {
                text: 'Energy (Watt)'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        series: [{
            name: 'Power Usage',
            data: [<?php echo $this->powerUsage; ?>]
        }, {
            name: 'Power Return',
            data: [<?php echo $this->powerReturn; ?>]
        }]
    });
});

$(function () {
    $('#daily_power').highcharts({
        plotOptions: {
            column: {
                stacking: 'normal'
            },
            series: {
                pointPadding: 0.1,
                groupPadding: 0,
                borderWidth: 0,
                shadow: false
            },
        },
        tooltip: {
            headerFormat: '<span>{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color}">{series.name}: </td>' +
            '<td><b>{point.y:.1f} KWh</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        title: {
            text: 'Daily energy usage'
        },
        subtitle: {
            text: 'last 30 days'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45
            }
        },
        yAxis: {
            title: {
                text: 'Energy (KWh)'
            }
        },
        series: [{
            type: 'column',
            name: 'Power Usage Total',
            data: [<?php echo $this->powerUsageTotal; ?>],
            color: 'red'
        }, {
            type: 'column',
            name: 'Power Return Total',
            data: [<?php echo $this->powerReturnTotal; ?>],
            color: 'green'
        }, {
            type: 'spline',
            name: 'Average',
            data: [<?php echo $this->powerAverage; ?>],
            marker: {
                lineWidth: 1,
                lineColor: Highcharts.getOptions().colors[3],
                fillColor: 'white'
            }
        }]
    });
});

$(function () {
    $('#daily_gas').highcharts({
        chart: {
            type: 'column'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: false
                }
            }
        },
        title: {
            text: 'Daily gas usage'
        },
        subtitle: {
            text: 'last 30 days'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45
            }
        },
        yAxis: {
            title: {
                text: 'Gas (m3)'
            },
            plotLines: [{
                value: 0,
                width: 1
            }]
        },
        series: [{
            name: 'Gas Usage Total',
            data: [<?php echo $this->gasTotal; ?>]
        }]
    });
});
</script>

<div class="row">
    <div class="col-md-12" id="power" style="min-width: 310px; height: 400px; margin-top: 20px"></div>
</div>
<div class="row">
    <div class="col-md-12" id="daily_power" style="min-width: 310px; height: 400px; margin-top: 20px"></div>
</div>
<div class="row">
    <div class="col-md-12" id="daily_gas" style="min-width: 310px; height: 400px; margin-top: 20px"></div>
</div>
